version: '3.8'

services:
  cardinal-embedding-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cardinal-embedding-processor
    ports:
      - "18080:8080" # Внешний порт:внутренний порт контейнера (из Dockerfile ENV ASPNETCORE_URLS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # Или Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=emb_proc;Username=app;Password=YRyGe6K1SneslitROY7PxA
      - EmbeddingsApi__Host=http://embeddings:80 # Адрес сервиса эмбеддингов
      - Qdrant__Host=http://qdrant:6333 # Адрес Qdrant REST API
      - Qdrant__CollectionName=leads # Имя коллекции Qdrant
      - ApiKey=d4f8c9b1-8a7b-4e6e-9f0d-0c1b2a3f4e5d # Ключ API для аутентификации
      - Qdrant__ApiKey=a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d # Ключ API для Qdrant
      # Новые параметры поиска (закомментированы, будут использоваться значения по умолчанию из appsettings.json, если не заданы здесь)
      # - Search__TopN=1000
      # - Search__ScoreThreshold=0.85
      # - Search__BayesianAlpha=1.0
      # - Search__BayesianBeta=1.0
      # - Search__MinGroupScoreSumThreshold=0.6
    depends_on:
      - postgres
      - qdrant
      - embeddings
    restart: unless-stopped

  embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.4
    container_name: embeddings-service
    environment:
      - MODEL_ID=intfloat/multilingual-e5-base
      - NUM_WORKERS=2 # Настройте в соответствии с вашими ресурсами CPU
      - POOLING=mean
    ports:
      - "10080:80"
    volumes:
      - embeddings_data:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    restart: unless-stopped
    ports:
      - "10633:6333" # REST API
      - "10634:6334" # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: YRyGe6K1SneslitROY7PxA # Используем сгенерированный пароль
      POSTGRES_DB: emb_proc
    ports:
      - "10543:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  qdrant_data:
  embeddings_data:

