services:

  app:
    image: 162.120.16.215:54710/cardinal/app:0.0.3-SNAPSHOT
    restart: unless-stopped
    ports:
      - "3000:3000"

  telegram-parser:
    image: 162.120.16.215:54710/cardinal/telegram-parser:0.0.3-SNAPSHOT
    restart: unless-stopped
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      PYRO_SESSION: cardinal_1
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - pyrogram-sessions:/app/pyrogram-sessions
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  message-processor:
    image: 162.120.16.215:54710/cardinal/message-processor:0.0.3-SNAPSHOT
    restart: unless-stopped
    environment:
      ENABLE_METRICS: ${ENABLE_METRICS}
      LANGSMITH_TRACING: true
      LANGSMITH_PROJECT: cardinal
      LANGSMITH_ENDPOINT: https://api.smith.langchain.com
      BACKEND_CORE_HOST: http://cardinal-backend-core-1:8000
      EMBEDDINGS_PROCESSOR_HOST: http://cardinal-embeddings-processor-1:8080
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_HOST: ${POSTGRESQL_HOST}
      DB_NAME: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASS: ${POSTGRESQL_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      MIN_CONFIDENCE: ${MIN_CONFIDENCE}
      BACKEND_CORE_KEY: ${BACKEND_CORE_KEY}
      EMBEDDINGS_PROCESSOR_KEY: ${EMBEDDINGS_PROCESSOR_KEY}
    depends_on:
      - redis
      - rabbitmq
      - postgresql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  embeddings-processor:
    image: 162.120.16.215:54710/cardinal/embeddings-processor:0.0.3-SNAPSHOT
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Qdrant__CollectionName: leads
      Qdrant__Host: http://cardinal-qdrant-1:6333
      EmbeddingsApi__Host: http://cardinal-embeddings-1:80
      Qdrant__ApiKey: ${QDRANT_KEY}
      ApiKey: ${EMBEDDINGS_PROCESSOR_KEY}
      ConnectionStrings__Postgres: ${EMBEDDINGS_PROCESSOR_DB_CONNECTION_STRING}
      Search__ScoreThreshold: 0.86
    depends_on:
      - qdrant
      - embeddings
      - embeddings-postgresql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend-core:
    image: 162.120.16.215:54710/cardinal/backend-core:0.0.3-SNAPSHOT
    restart: unless-stopped
    environment:
      ENABLE_METRICS: ${ENABLE_METRICS}
      WEBHOOK_URL: https://cardinal-x.online
      AI_CORE_HOST: http://cardinal-ai-core-1:8000
      EMBEDDINGS_PROCESSOR_HOST: http://cardinal-embeddings-processor-1:8080
      BOT_TOKEN: ${BOT_TOKEN}
      RECOMMENDATION_BOT_TOKEN: ${RECOMMENDATION_BOT_TOKEN}
      WEBHOOK_KEY: ${TG_WEBHOOK_KEY}
      DB_HOST: ${POSTGRESQL_HOST}
      DB_NAME: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASS: ${POSTGRESQL_PASS}
      ALPHA_KEY: ${ALPHA_KEY}
      LAVA_KEY: ${LAVA_KEY}
      LAVA_X_KEY: ${LAVA_WEBHOOK_KEY}
      ROBOKASSA_PASS_1: ${ROBOKASSA_PASS_1}
      ROBOKASSA_PASS_2: ${ROBOKASSA_PASS_2}
      SECURITY_KEY: ${SECURITY_KEY}
      AI_CORE_KEY: ${AI_CORE_KEY}
      API_KEY: ${BACKEND_CORE_KEY}
      EMBEDDINGS_PROCESSOR_KEY: ${EMBEDDINGS_PROCESSOR_KEY}
      SELARTI_AUTH_HOST: ${SELARTI_AUTH_HOST}
      SELARTI_TARGET_HOST: ${SELARTI_TARGET_HOST}
      SELARTI_KEY: ${SELARTI_KEY}
      SELARTI_TASK: ${SELARTI_TASK}
    depends_on:
      - postgresql
      - ai-core
      - embeddings-processor
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "8000:8000"

  ai-core:
    image: 162.120.16.215:54710/cardinal/ai-core:0.0.3-SNAPSHOT
    restart: unless-stopped
    environment:
      ENABLE_METRICS: ${ENABLE_METRICS}
      AI_MODE: prod
      LANGSMITH_TRACING: true
      LANGSMITH_PROJECT: cardinal
      LANGSMITH_ENDPOINT: https://api.smith.langchain.com
      API_KEY: ${AI_CORE_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      SECURITY_KEY: ${SECURITY_KEY}
      DB_HOST: ${POSTGRESQL_HOST}
      DB_NAME: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASS: ${POSTGRESQL_PASS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "8088:8000"

  qdrant:
    image: qdrant/qdrant:v1.15.4
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_KEY}
    volumes:
      - qdrant-data:/qdrant/storage
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: cardinal
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:8.4.0-alpine3.22
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: >
      sh -c "redis-server
      --save 60 3000
      --loglevel warning
      --requirepass $REDIS_PASSWORD"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    restart: unless-stopped
    environment:
      - MODEL_ID: intfloat/multilingual-e5-base
      - NUM_WORKERS: 2
      - POOLING: mean
      - MAX_CLIENT_BATCH_SIZE: 1000
    volumes:
      - embeddings-data:/data
    deploy:
      resources:
        limits:
          memory: 6GB
        reservations:
          memory: 4GB

  postgresql:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_DB: cardinal
      POSTGRES_USER: cardinal
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  embeddings-postgresql:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_DB: cardinal
      POSTGRES_USER: cardinal
      POSTGRES_PASSWORD: ${EMBEDDINGS_PROCESSOR_POSTGRESQL_PASS}
    volumes:
      - embeddings-postgresql-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  redis-data:
  qdrant-data:
  rabbitmq-data:
  embeddings-data:
  postgresql-data:
  embeddings-postgresql-data:
  pyrogram-sessions:
    external: true
