version: '3.8'

services:
  telegram-parser:
    image: registry.develixtech.com/cardinal/telegram-parser:0.0.3-SNAPSHOT
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
      RABBITMQ_PASS:
    depends_on:
      - rabbitmq


  message-processor:
    image: registry.develixtech.com/cardinal/message-processor:0.0.3-SNAPSHOT
    environment:
      DB_PASS:
      RABBITMQ_PASS:
      REDIS_PASSWORD:
      OPENAI_API_KEY:
      BACKEND_CORE_KEY:
      BACKEND_CORE_HOST:
      EMBEDDINGS_PROCESSOR_KEY:
      EMBEDDINGS_PROCESSOR_HOST:
    depends_on:
      - redis
      - rabbitmq
      - postgresql

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: cardinal
      RABBITMQ_DEFAULT_PASS: 
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:8.4.0-alpine3.22
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: >
      sh -c "redis-server
      --save 60 3000
      --loglevel warning
      --requirepass $REDIS_PASSWORD"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgresql:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_DB: cardinal
      POSTGRES_USER: cardinal
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  redis-data:
  rabbitmq-data:
  postgresql-data:
